name: Vanish
main: de.myzelyam.supervanish.SuperVanish
author: MyzelYam
description: Advanced /vanish plugin which makes other players think that you're not on the server
version: ${project.version}
api-version: 1.13
website: https://www.spigotmc.org/resources/supervanish-be-invisible.1331/
softdepend:
- ProtocolLib
- LibsDisguises
- DisguiseCraft
- dynmap
- Essentials
- TrailGUI
- PlaceholderAPI
- CustomParticleEffects
- NametagEdit
- MVdWPlaceholderAPI
- Vault
commands:
  v:
    usage: /v
    description: SuperVanish's main command
    aliases: [supervanish, v, vanish]
permissions:
  v.*:
    children:
      v.use: true
      v.see: true
      v.reload: true
      v.logout: true
      v.login: true
      v.others: true
      v.list: true
      v.keepfly: true
      v.toggleitems: true
      v.recreatefiles: true
      v.notoggle: true
      v.joinvanished: true
      v.notify: true
      v.breakblocks: true
      v.placeblocks: true
      v.damage: true
      v.stacktrace: true
      v.silentchest: true
    description: Grants you all SuperVanish permissions
  supervanish.*:
    children:
      v.*: true
    description: Grants you all SuperVanish permissions
  v.see:
    description: You can see other vanished players
  v.notoggle:
    description: Other players cannot hide/show you if you're online
  v.keepfly:
    description: You can always keep flying when you reappear
  v.joinvanished:
    description: You always join vanished (must be enabled in config)
  v.silentchest:
    description: You can open chests silently